language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

script:
  - cd src
  - ./configure
  - make

jobs:
  include:
    - stage: analyze
      name: flawfinder
      os: linux
      script: flawfinder .
      addons:
        apt:
          update: true
          packages:
            - flawfinder
    - stage: analyze
      name: cppcheck
      os: linux
      script: cppcheck --force .
      addons:
        apt:
          update: true
          packages:
            - cppcheck
    - stage: analyze
      name: infer
      dist: bionic
      compiler: clang
      script:
        - VERSION=1.0.0
        - curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" | sudo tar -C /opt -xJ
        - sudo ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer
        - cd src
        - ./configure
        - infer --progress-bar-style plain --quiet -- make
        - cat infer-out/bugs.txt
      addons:
        apt:
          update: true
          packages:
            - libstdc++6
