language: c

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

script:
  - cd src
  - ./configure
  - make

jobs:
  include:
    - stage: analyze
      name: flawfinder
      os: linux
      script: flawfinder .
      addons:
        apt:
          update: true
          packages:
            - flawfinder
      name: cppcheck
      os: linux
      script: cppcheck .
      addons:
        apt:
          update: true
          packages:
            - cppcheck